# Generated by Django 3.2.12 on 2024-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0010_alter_advertisement_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
