# Generated by Django 3.2.12 on 2024-10-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0011_pronoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_loctaions',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
