# Generated by Django 3.2.12 on 2024-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0014_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
