# Generated by Django 3.2.12 on 2025-08-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0017_alter_master_table_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsimage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsApp.organization'),
        ),
    ]
